title : Arjun Mani
author :
name : Arjun Mani
email : arjunsubm@gmail.com
github : arjun-mani

plugins:
  - jekyll-paginate

markdown: kramdown

paginate: 5
paginate_path: "/blog/page:num/"

permalink: /blog/:year/:month/:day/:title
excerpt_separator: "<!--excerpt-->"
